export default function About() {
    return (
      <div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
        <div>Hashir</div>
      </div>
    );
}  